bot:
  token: ${BOT_TOKEN}
  prefix: ${BOT_PREFIX}
  status: ${BOT_STATUS}
  log_level: ${LOG_LEVEL}
openai:
  api_key: ${OPENAI_API_KEY}
database:
  username: ${MONGO_USERNAME}
  password: ${MONGO_PASSWORD}
  hostname: ${MONGO_HOSTNAME}
  port: ${MONGO_PORT}
  database_name: ${MONGO_INITDB_DATABASE}
