bot:
  token: "your_bot_token"
  prefix: "!"
  status: "your commands!"
  log_level: INFO
database:
  username: ${MONGO_USERNAME}
  password: ${MONGO_PASSWORD}
  hostname: ${MONGO_HOSTNAME}
  port: ${MONGO_PORT}
  database_name: ${MONGO_INITDB_DATABASE}
