bot:
  token: your_bot_token
  prefix: "!"
  status: "your commands!"
  log_level: "INFO"
  webhook_url: "https://canary.discord.com/api/webhooks/000000000000000000/xxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
roles:
  professor: 0000000000000000000
database:
  username: !ENV ${MONGO_USERNAME}
  password: !ENV ${MONGO_PASSWORD}
  hostname: !ENV ${MONGO_HOSTNAME}
  port: !ENV ${MONGO_PORT}
  database_name: !ENV ${MONGO_INITDB_DATABASE}
