version: "3.8"
services:
  cpr:
    container_name: cpr
    image: ghcr.io/lunarmint/cpr:latest
    restart: unless-stopped
    env_file: .env
    volumes:
        - ./config.yml:/app/config.yml
        - ./logs:/app/logs/
    depends_on:
        - mongo
  mongo:
    image: mongo:6.0.2
    container_name: mongo
    command: mongod --port ${MONGO_PORT}
    restart: unless-stopped
    env_file: .env
    volumes:
        - ./db:/data/db
    ports:
      - "127.0.0.1:${MONGO_PORT}:${MONGO_PORT}"
